# Generated by Django 4.1.5 on 2023-06-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rating_created_at_rating_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="tag",
            new_name="main_tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="store.tag"),
        ),
    ]
