# Generated by Django 4.1.5 on 2023-06-11 17:48

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_tag_rename_tag_product_main_tag_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image1",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image2",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image3",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image4",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image5",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.get_file_path
            ),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.tag"
                    ),
                ),
            ],
        ),
    ]
