# Generated by Django 4.1.5 on 2023-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_brand_brand_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(to="store.tag"),
        ),
    ]
